### PR TITLE
[SA-10] Sound and music buttons actions are mixed up

### LINKED ISSUE #18: [SA-10] Sound and music buttons actions are mixed up
On the main menu screen try to tap on sound and music buttons

**Expected result**
Sound is affected by sound button and music is affected by music button

**Actual result**
These actions are mixed up

### PR DESCRIPTION
**Pull request by alexkats**
Fixes #18 #19 #20 #22

### CODE REVIEW

**Review by terradrenor — CHANGES_REQUESTED** [review]
Seems that 2 other sound files for asteroid crash are unused

**Comment by alexkats** [comment]
Let them be for now, maybe we will you random of 3 files each time you destroy asteroid

**Review by terradrenor — APPROVED** [review]
OK

**Comment by cover63** [comment]
Hey

**Comment by cover63** [comment]
How atre you ?

**Pull request merged**
